name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - 
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    -
      name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3
    -
      name: Build and Push Image
      uses: docker/build-push-action@v5
      with:
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/ptt:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/ptt:latest
          cache-to: type=inline
